site_name: SailbotVT Documentation
site_url: https://localhost:8000

nav:
  - Home: index.md

  - Getting Started: 
    - Installing Docker: getting_started/installing_docker.md
    - Setting Up the Development Container: getting_started/setting_up_dev_environment.md
    - What Did You Just Install?: getting_started/what_did_you_just_install.md
    - Installing MicroROS: getting_started/installing_microros.md

  - Examples:
    - Running the Simulation: examples/running_simulation.md
    - Running a Custom Simulation: examples/running_a_custom_simulation.md
    - Running Individual Nodes for Testing: examples/running_individual_nodes.md
    - Connecting A USB Device to WSL: examples/connecting_a_usb_device_to_wsl.md
    - Adding Documentation: examples/adding_documentation.md
    - Adding A New ROS2 Package to the Workspace: examples/adding_a_new_ros2_node.md
    - Adding a New ROS2 Node to A Package: examples/adding_a_new_ros2_package.md
    - Adding A New External Library that We Can Edit: examples/how_we_handle_external_libraries.md

  - System Diagrams:
    - Flow of Information Between Groundstation and Autopilot Node: system_diagrams/diagram_of_groundstation_telemetry.md
    - Diagram of How the Simulation Works and Communicates with ROS: system_diagrams/diagram_of_simulations.md
    - ROS2 Node Diagrams: system_diagrams/diagram_of_ros_nodes.md

  - Hardware:
    - Wiring Color Scheme: hardware/wiring_color_scheme.md
    - Squircuit: hardware/squircuit.md


  - ROS2 Packages and Nodes:

    - Autopilot Package: 
      - Common Documentation Between the Motorboat Autopilot and the Sailboat Autopilot: nodes/common_documentation_between_the_motorboat_autopilot_and_the_sailboat_autopilot.md
      - Sailboat Autopilot Node: nodes/sailboat_autopilot.md
      - Motorboat Autopilot Node: nodes/motorboat_autopilot.md
      - Telemetry: nodes/telemetry.md

    - Sensors Package:
      - GPS Node: nodes/gps.md
      - RC (Remote Controller) Node: nodes/rc.md
      - Wind Sensor Node: nodes/wind_sensor.md

    - VESC Package:
      - VESC Node: nodes/vesc.md

    - Microros Package:
      - Raspberry Pi Pico Microros Node: nodes/microros.md

    - Object Detection Package: 
      - Object Detection Node: nodes/object_detection.md
    
    - Sailbot Messages Package:
      - Sailbot Messages Node: nodes/sailbot_msgs.md
    
    - Simulation Package: 
      - Sailboat Simulation Node: nodes/sailboat_simulation.md
    
    - What About the Other Nodes: nodes/what_about_the_other_nodes.md

  - Misc:
    - Potential Security Risks: misc/potential_security_risks.md

  - Standards and Definitions: standards_and_definitions.md

  - Crontabs: crontabs.md

  - Known Issues: known_installation_issues.md



theme: 
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
# theme:
#   name: readthedocs

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.arithmatex:
      generic: true
  # If you want to re-enable highlighting and TOC:
  # - pymdownx.highlight:
  #     anchor_linenums: true
  #     line_spans: __span
  #     pygments_lang_class: true
  # - toc:
  #     toc_depth: "1-1"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
